nginx:
  image: dr.ytlabs.co.kr/nginx:1.7.9
#   command: bash -c "nginx;php-fpm -y /etc/php-fpm.conf"
  # command: bash -c "while [ 0 ]; do sleep 1;done"
  volumes:
    - ./www:/var/www/html
    # - ./logs:/var/log/nginx
    # - /etc/localtime:/etc/localtime:ro

  ports:
   - "9797:80"
   - "8443:443"

  environment:
    USE_DOCKERIZE: "yes"
    UPSTREAM: "100.100.100.188:9000"
    DOMAIN: "dev.yt.com"
    LOCATION: 'location ~* \.(?:css|js|ico|woff|eot|svg|ttf|otf|woff2) {
                access_log off;
                add_header Cache-Control public;
                expires 1w;
                }'
